
int main(void){

int a[1024] = "dfvgfdgdfsgsdfgsgsdfgdsgsgdsfgdgdfgfdgfdgfgfdsgdfsgsdgfsdghgdfhgffgsfgsgfsfdgdgdfgfdgfdgdfgdfgfgdgsdgsdgdssfgsddfvgfdgdfsgsdfgsgsdfgdsgsgdsfgdgdfgfdgfdgfgfdsgdfsgsdgfsdghgdfhgffgsfgsgfsfdgdgdfgfdgfdgdfgdfgfgdgsdgsdgdssfgsddfvgfdgdfsgsdfgsgsdfgdsgsgdsfgdgdfgfdgfdgfgfdsgdfsgsdgfsdghgdfhgffgsfgsgfsfdgdgdfgfdgfdgdfgdfgfgdgsdgsdgdssfgsddfvgfdgdfsgsdfgsgsdfgdsgsgdsfgdgdfgfdgfdgfgfdsgdfsgsdgfsdghgdfhgffgsfgsgfsfdgdgdfgfdgfdgdfgdfgfgdgsdgsdgdssfgsddfvgfdgdfsgsdfgsgsdfgdsgsgdsfgdgdfgfdgfdgfgfdsgdfsgsdgfsdghgdfhgffgsfgsgfsfdgdgdfgfdgfdgdfgdfgfgdgsdgsdgdssfgsddfvgfdgdfsgsdfgsgsdfgdsgsgdsfgdgdfgfdgfdgfgfdsgdfsgsdgfsdghgdfhgffgsfgsgfsfdgdgdfgfdgfdgdfgdfgfgdgsdgsdgdssfgsdvfbgvfdgdvfdfvgfdgdfsgsdfgsgsdfgdsgsgdsfgdgdfgfdgfdgfgfdsgdfsgsdgfsdghgdfhgffgsfgsgfsfdgdgdfgfdgfdgdfgdfgfgdgsdgsdgdssfgsddfvgfdgdfsgsdfgccsdddvdfsavafdvadfvsgsdfgdsgsgdsfgdgdfgfdgfdgfgfdsgdfsgsdgfsdghgdfhgffgsfgsgfsfdgdgdfgfdgfdgdfgdfgfgdgsdgsdtgfgfggbvgfbthsfgbdhgshgdssfgsddfvgfdgdfsgsdfgsgsdfgdsgsgdsfgdgfdgfdgfgfdsgdfsgsdgfsdghgdfhgfggsdgagadfagghgadgdf";
char b='b';
return 0;
}