KR_INT 1 int
IDN 1 xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
TOCKAZAREZ 1 ;
KR_INT 2 int
IDN 2 yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy
TOCKAZAREZ 2 ;
KR_INT 4 int
IDN 4 main
L_ZAGRADA 4 (
KR_VOID 4 void
D_ZAGRADA 4 )
L_VIT_ZAGRADA 4 {
KR_INT 5 int
IDN 5 zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz
TOCKAZAREZ 5 ;
KR_INT 6 int
IDN 6 wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww
TOCKAZAREZ 6 ;
KR_INT 7 int
IDN 7 qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq
TOCKAZAREZ 7 ;
KR_RETURN 8 return
BROJ 8 0
TOCKAZAREZ 8 ;
D_VIT_ZAGRADA 9 }
